# Generated by Django 2.2.5 on 2019-12-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.CharField(max_length=20, null=True)),
                ('mon_raised', models.IntegerField(default=0)),
            ],
        ),
    ]
