# Generated by Django 2.2.2 on 2019-10-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('team', models.CharField(default='', max_length=100)),
                ('points', models.IntegerField(blank=True, default=0)),
                ('mon_raised', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['joined'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('team', models.CharField(default='', max_length=100)),
                ('points', models.IntegerField(blank=True, default=0)),
                ('mon_raised', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['joined'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('joined', models.DateField(null=True)),
                ('team', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ['joined'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('team', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=50)),
                ('points', models.IntegerField(blank=True, default=0)),
                ('mon_raised', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'ordering': ['joined'],
                'abstract': False,
            },
        ),
    ]
