# Generated by Django 2.2.2 on 2019-12-02 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('place', models.CharField(max_length=180)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
